Task4.1
davxis/TekanovFedorTki142 pull request #14
Opened 2024-11-25 09:30 UTC by davxis

#13

2024-11-25 11:08 UTC, BalakinaEP requested changes

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int A = inputInt("A: ");
Что это такое, со строчной буквы

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int sumOfNegs, posAndLesOrEqA, lastPair;
Убрать

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int* ar = allocIntArray(n);
неправильно выделяете память

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int choice = inputInt("choice (1 - random, other - keyboard): ");
нет проверки, что память выделена

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    if (choice == 1) {
константа в коде

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int choice = inputInt("choice (1 - random, other - keyboard): ");
константы в коде

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    *lastPair = determineLastPairOfDiffSigns(ar, n);
Убрать функцию, все в main

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int* ar = allocIntArray(n);
allocIntArray

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n - 1; i++) {
size_t

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    for (int i = 0; i < n - 1; i++) {
не соответствует заданию

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    int n = inputInt("n: ");
size_t и проверят ь, что введенное значение положительное

2024-11-25 11:08 UTC, BalakinaEP commented on Task4.1.c
> +    }
В отдельную функцию
Во всех функциях, где используется массив, сначала должна быть эта проверка

2024-11-30 10:42 UTC, davxis commented on Task4.1.c
> +    int choice = inputInt("choice (1 - random, other - keyboard): ");
Проверка на то, что память действительно была выделена есть в реализации функции allocIntArray

2024-12-04 10:03 UTC, BalakinaEP commented on Task4.1.c
> +    int* ar = allocIntArray(n);
Размер выделяемой памяти

2024-12-09 10:57 UTC, BalakinaEP requested changes

2024-12-09 10:57 UTC, BalakinaEP commented on Task4.1.c
> +    }
siwitch case

2024-12-09 10:57 UTC, BalakinaEP commented on Task4.1.c
> +    enum choice choice = (enum choice) inputInt("choice (1 - random, other - keyboard): ");
константы в коде

2024-12-09 10:57 UTC, BalakinaEP commented on Task4.1.c
> +    int lastPair = determineLastPairOfDiffSigns(ar, n);
В main

2024-12-09 10:57 UTC, BalakinaEP commented on Task4.1.c
> +}
не нужна

2024-12-09 10:57 UTC, BalakinaEP commented on Task4.1.c
> +        printf("no pairs with different signs\n");
В main

2024-12-16 12:36 UTC, BalakinaEP requested changes

2024-12-16 12:36 UTC, BalakinaEP commented on Task4.1.c
> +    }
CHOICE_KEYBOARD
default

2024-12-16 12:36 UTC, BalakinaEP commented on Task4.1.c
> +    }
В отдельную функцию

2024-12-16 12:36 UTC, BalakinaEP commented on Task4.1.c
> +    }
Вставить ее во все функции, в которые в качестве параметра передается массив (любой)

2024-12-16 12:36 UTC, BalakinaEP commented on Task4.1.c
> +        if (ar[i] < 0 != ar[i + 1] < 0) {
(ar[i] * ar[i + 1] < 0)

2024-12-16 12:36 UTC, BalakinaEP commented on Task4.1.c
> +    for (size_t i = 0; i < n - 1; i++) {
```
int determineLastPairOfDiffSigns(const int* ar, const size_t n) {
for (size_t i = n-1; i >= 0; i--)
{
    if (ar[i] * ar[i + 1] < 0)
      {return i+1}
}
return -1;

```

2024-12-18 09:42 UTC, MarinaPaley approved these changes
Код с недостатками, но самостоятельность работы под большим вопросом(

2024-12-18 09:44 UTC, merged